apiVersion: apps/v1
kind: ReplicaSet
metadata: 
name: rsp-nginx
spec:
replicas: 2
selector:
matchlabels:
app: web
template:
metadata:
name: nginx
labels:
app: web
spec:
containers:
- name: container-nginx
image: vishal1992/jenkin:first
ports:
- containerport: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-npp
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 8080
    nodePort: 31000
  selector:
    apps: web
