apiVersion: v1
kind: ReplicaSet
metadata: 
name: rs-nginx
spec:
replicas: 2
selector:
matchlabels:
app: web
template:
metadata:
name: nginx
labels:
app: web
spec:
containers:
- name: container-nginx
image: vishal1992/jenkin:first
ports:
- containerport: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-kb
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    nodePort: 31000
  selector:
    app: web
