apiVersion: apps/v1
kind: ReplicaSet
metadata: 
name: rs-nginx
spec:
replicas: 2
selector:
matchlabels:
app: web
template:
metadata:
name: nginx
labels:
app: web
spec:
containers:
- name: container-nginx
image: nginx
ports:
- containerport: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 8080
    nodePort: 31000
  selector:
    apps: web
