apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: vishal1992/jenkin:first
      labels:
        app: web
    spec:
      containers:
      - name: container-nginx
        image: vishal1992/jenkin:first
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-kb
  namespace: default
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    nodePort: 31500
  selector:
    app: web
